#!/usr/bin/env python3

from gi.repository import Clutter, Pango

def create_label(color, markup):
	text = Clutter.Text()
	
	text.set_color(Clutter.Color.from_string(color))
	text.set_markup(markup)
	text.set_editable(False)
	text.set_selectable(False)
	text.set_single_line_mode(True)
	text.set_ellipsize(Pango.EllipsizeMode.END)

	return text

def create_entry(color, passchar, maxlength):
	text = Clutter.Text()
	
	text.set_color(Clutter.Color.from_string(color))
	text.set_reactive(True)
	text.set_editable(True)
	text.set_selectable(True)
	text.set_activatable(True)
	text.set_password_char(passchar)
	text.set_cursor_color(Clutter.Color.from_string("#FFFFFF"))
	text.set_selected_text_color(Clutter.Color.from_string("#CCCCCC"))
	text.set_single_line_mode(True)
	text.set_max_length(maxlength)

	# text.connect("activate", on_entry_activate)
	# text.connect("paint", on_entry_paint)
	# text.connect("captured-event", on_captured_event)

	return text


if __name__ == "__main__":
	stage = Clutter.Stage()

	stage.set_color(Clutter.Color.from_string("#000000"))
	stage.set_size(1024, 768)
	stage.set_title("Text Fields")
	stage.connect("destroy", Clutter.main_quit)

	table = Clutter.TableLayout()

	table.set_column_spacing(6)
	table.set_row_spacing(6)

	box = Clutter.Box(table)

	box.add_constraint(Clutter.BindConstraint.new(stage, Clutter.BindCoordinate.WIDTH, -24))
	box.add_constraint(Clutter.BindConstraint.new(stage, Clutter.BindCoordinate.HEIGHT, -24))
	box.set_position(12, 12)

	box.pack(
		create_label("#FFFFFF", "<b>Input field:</b>"),
		row=0,
		column=0,
		x_expand=False,
		y_expand=False
	)

	box.pack(
		create_entry("#cccccc", '*', 0),
		row=0,
		column=1,
		x_expand=True,
		x_fill=True,
		y_expand=False
	)

	stage.add_actor(box)
	# stage.set_key_focus(text)
	stage.show_all()

	Clutter.main()

