#!/usr/bin/env python3

import gi.types

from gi.repository import Clutter

def recurse_gobject(gobj, indent=0):
	print("%s%s" % ("\t" * indent, gobj))

	indent += 1

	for d in dir(gobj):
		try:
			obj = getattr(gobj, d)

		except:
			continue
		
		if type(obj) in (gi.types.GObjectMeta, gi.types.StructMeta):
			recurse_gobject(obj, indent)

		else:
			print("%s%s = %s" % ("\t" * indent, d, type(obj)))

if __name__ == "__main__":
	recurse_gobject(Clutter)

